### ISSUE TITLE
文字の出るスピードが早くなっていく。

### ISSUE THREAD

**Issue by novogrammer** [024t910/quiz_2020#1]
qtimerがクリアされていないので、文字の出るスピードがどんどん早くなっていきます。
グローバル変数なので、setIntervalを呼び出す直前にクリアすることでひとまず解決できると思います。
https://github.com/024t910/quiz_2020/blob/master/index.html#L105

**Comment by 024t910** [comment]
@novogrammer 
ご指摘、ありがとうございますー！直しておきます！
