### ISSUE TITLE
不自然なタイミングでtimeOutHandlerが呼び出される。

### ISSUE THREAD

**Issue by novogrammer** [024t910/quiz_2020#2]
関数名timeOutHandlerと似たtimeoutHandler変数がクリアされていることが無いため、出題中であろうと、突然タイトルに戻ります。

仕様は想像するしか無いですが、
以下の三状態を遷移するため、正解表示時にtimeoutHandlerをクリアすることで、半無限クイズ状態になると思います。

・タイトル画面（初期状態）
->スタートで出題へ遷移
・出題
->音声入力があれば正解表示
->タイムアウトでタイトル画面
・正解表示
->タイムアウトで出題

タイムアウトなしでタイトルに戻らさせないのもアリかと思いました。

**Comment by 024t910** [comment]
@novogrammer 
ありがとうございます！
本件commit 312cd3f にて修正済みです。

リアル展示用途も兼ねているため、一定時間回答がない場合タイトルに戻すと言う意図の処理でした
